# specify language
language: java
jdk:
- openjdk8
install:
- mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
- mvn clean test
after_success:
- bash <(curl -s https://codecov.io/bash)